# 100-case representative subset of tests/tests_core.py  (generated 2026-06-04)
# 12 cases per phase (16 for Phase IV; II=13, VII=11). Type totals across all 100: 25 True / 25 False / 24 Unknown(None) / 26 concrete.
# Per-phase (True/False/None/concrete): I 4/3/3/2  II 3/3/3/4  III 3/4/3/2  IV 4/4/4/4  V 4/3/2/3  VI 3/4/2/3  VII 1/1/4/5  VIII 3/3/3/3.
# Cases spread across subsections and spaced to avoid near-neighbours.
[

# === PHASE I: FOUNDATIONS  (T4 F3 N3 C2) ===
  [2, 'Elephants are animals. John is an elephant. John is an animal?', True],
  [47, 'A very big mouse is nice. The mouse is a very big mouse?', True],
  [70, 'Elephants have trunks or tails. John is an elephant. John has no trunk. John has a tail?', True],
  [5, 'Elephants are not birds. John is an elephant. John is a bird?', False],
  [15, 'John is a tall man and not a tall man?', False],
  [8, 'Elephants are big animals. John is an elephant. Who is nice?', None],
  [21, 'John is in Estonia?', None],
  [6, 'Elephants are animals. Who is an animal?', 'An elephant.'],
  [28, 'Yellow and green elephants are nice. John is an elephant. John is yellow and green. John is nice?', 'Probably true.'],
  [36, 'John is somewhat big. John is big?', True],
  [22, 'John is glad. If John is glad, then Mike is not glad. Is Mike glad?', False],
  [61, 'The car is red. The bike is small. Is the bike red?', None],

# === PHASE II: REFERENCE & POSSESSION  (T3 F3 N3 C4) ===
  [134, 'An apple was bad. She was in a room. She was in the room?', True],
  [470, 'The length of the red car is 3 meters. The length of the black car is 5 meters.\n      The length of the red car is less than the length of the black car?', True],
  [234, "The roof of John's house is green. John has a house?", True],
  [117, 'Americans can not disappear. Mr Dursley is an American. Mr Dursley can disappear?', False],
  [193, 'Elephants have no long red trunks. John is an elephant. John has a long red trunk?', False],
  [250, 'The bicycle of Tom was new. Was the bicycle old?', False],
  [136, 'An apple was bad. She was in a room. An apple was in a room?', None],
  [184, 'Elephants have a trunk. Birds have a trunk?', None],
  [228, "John's brother has a car. John's sister has a car?", None],
  [107, 'A boy saw a girl. He was nice. Who was nice?', ['The boy', 'The nice boy']],
  [190, 'Elephants have long grey trunks. John is an elephant. Who has a grey trunk?', 'John.'],
  [248, "Mary's uncle arrived. Who has an uncle?", 'Mary.'],
  [409, 'John has three nice cars. How many nice cars does John have?', ['Three', '3.']],

# === PHASE III: QUANTIFIERS & COMPARISON  (T3 F4 N3 C2) ===
  [524, 'John likes all boxers. Mike is a boxer. John likes Mike?', True],
  [541, 'The red square has a nail. A blue square has a hole. A blue square has a hole?', True],
  [552, "John is as tall as Bill. Is John's height equal to Bill's?", True],
  [511, 'All elephants are animals. Elephants are not animals?', False],
  [536, 'Elephants are animals. All elephants are not animals?', False],
  [519, 'Some elephants are animals. Some elephants are not animals?', None],
  [542, 'The red square has a nail. A blue square has a hole. A red square has a hole?', None],
  [550, 'The red car is faster than the blue car. Is the green car faster than the red car?', None],
  [526, 'Bears eat most boxers. Mike is a boxer. Greg is a bear. Bears eats Mike?', 'Probably true.'],
  [546, 'Most bears are big. John is a bear. John is big?', 'Likely true.'],
  [523, 'No elephant is an animal. Some elephant is an animal?', False],
  [553, 'The mountain is higher than the hill. Is the hill higher than the mountain?', False],

# === PHASE IV: MODIFICATION & STRUCTURE  (T4 F4 N4 C4) ===
  [561, 'Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is not a bird?', True],
  [598, 'John bought a red car and a blue bicycle. The bicycle was blue?', True],
  [822, 'John has a car which is nice and red. The red car is nice?', True],
  [562, 'Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is a small fish?', False],
  [605, 'The students studied hard and passed the exam. Did the students fail the exam?', False],
  [671, 'The woman holding a heavy lamp sang. The lamp was light?', False],
  [893, 'The student who passed the test studied a lot. Did the student fail the test?', False],
  [588, 'A tall and quiet man entered. A woman entered?', None],
  [656, 'The child wearing a hat ran. The child wore a coat?', None],
  [829, 'John had a car which Eve bought. John had a car Mike bought?', None],
  [612, 'John bought a red car and a blue bicycle. What did John buy?', 'A red car and a blue bicycle'],
  [747, 'Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish who are strong?', [True, 'Likely true']],
  [979, 'John works at the hospital every day. Where does John work?', 'At the hospital.'],
  [663, 'The children playing in the garden laughed. The children were in the garden?', True],
  [975, 'Mary visited London in September. Did Mary visit Paris?', None],
  [888, 'The book that Mary bought is on the table. Who bought the book?', 'Mary.'],

# === PHASE V: CLAUSE ALTERNATIONS  (T4 F3 N2 C3) ===
  [1029, 'The letter was written by Eve. Eve wrote the letter?', True],
  [1054, 'The bill was paid by John. Did John pay the bill?', True],
  [1069, 'Although John was tired, he finished the work. John finished the work?', True],
  [1094, 'John bought a book, and Bill said Peter did too. Did Bill say Peter bought a book?', True],
  [1011, 'John is defeated. John is not defeated?', False],
  [1052, 'The city was destroyed. Is the city intact?', False],
  [1074, 'Though Mary was ill, she traveled. Mary did not travel?', False],
  [1032, 'The house was built by Tom. Tom destroyed the house?', None],
  [1049, 'Mary was given a promotion. Who received a promotion?', 'Mary.'],
  [1085, 'A surgeon, Dr. Smith, entered the room. Who entered the room?', ['Dr. Smith.', 'A surgeon.']],
  [1089, 'John went to Paris and Mary to London. Where did Mary go?', ['London.', 'To London.']],
  [1059, 'Eve reported that Tom arrived. Did Tom depart?', None],

# === PHASE VI: EVENTS & STATE  (T3 F4 N2 C3) ===
  [1112, 'Bears quickly eat berries in a deep forest. John is a bear. John quickly eats berries in a deep forest?', True],
  [1156, 'The teacher showed the students a map. The students saw a map?', True],
  [1188, 'While John was cooking, Mary read a book. Mary read a book?', True],
  [1099, 'Bears do not eat berries in a forest. Bears eat berries in a forest?', False],
  [1173, 'John has finished his homework. Is the homework unfinished?', False],
  [1206, 'John stopped smoking. Does John smoke now?', False],
  [1239, 'Tallinn is in Estonia. Estonia is not outside Europe. Earth contains Europe.\n       Estonia contains Tartu. Riga is not in Estonia. Riga is in Estonia?', False],
  [1149, 'Susan bought herself a new car. Did Tom buy a car?', None],
  [1146, 'The chef cooked a meal for the guests. Who was the meal for?', 'The guests.'],
  [1310, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Mary went to the bathroom. Sandra moved to the garden. Where is Sandra?', ['garden', 'In the garden.', 'At the garden.']],
  [1315, 'Eve planned to travel. Eve traveled?', None],
  [1176, 'The train leaves at noon. When does the train leave?', 'At noon.'],

# === PHASE VII: QUESTIONS  (T1 F1 N4 C5) ===
  [1316, 'John is nice. Is it true that John is nice?', True],
  [1317, 'John is nice. Is it false that John is nice?', False],
  [1332, 'John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which man has a potato?', None],
  [1326, 'Ellen is fond of John. Who is Ellen afraid of?', None],
  [1336, 'John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which bad man has a pear?', None],
  [1340, 'Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals.\n      Which animal cannot fly?', 'A fox'],
  [1329, 'John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which man has an apple?', 'John'],
  [1335, 'John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which nice man has a pear?', 'Mike'],
  [1341, 'Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals.\n      Which can fly?', 'A squirrel'],
  [1338, 'John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which nice man has an apple and a pear?', None],
  [1318, 'John Sweeney is a car. John Smith is bad. Who is John Sweeney?', 'A car.'],

# === PHASE VIII: REASONING  (T3 F3 N3 C3) ===
  [1370, 'If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals.\n    John is badly defeated. John is weak?', True],
  [1427, 'Penguins are birds. Penguins do not fly. Birds fly. John is a penguin. John is a bird?', True],
  [1429, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird.\n    John does not fly?', True],
  [1375, 'If an animal is cool and defeated then it is green.\n   John is an animal. John is cool.\n   Mike is an animal. Mike is cool. John is defeated. John is not green?', False],
  [1424, 'Penguins are birds. Penguins do not fly. Birds fly. Penguins fly?', False],
  [1408, 'Penguins are birds. Penguins do not fly. Birds fly. John is a penguin. John flies?', False],
  [1389, 'If animal or bird is nice and simple, it is cute. John is cute?', None],
  [1539, 'John is an elephant with a probability 50 percent. John is an elephant?', None],
  [1475, 'If a bear eats red berries, it is big. John eats berries. John is a bear.\n     John is big?', None],
  [1365, 'If X1 is a father of Y1, Y1 is a child of X1.\n      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1.\n      John is a father of Mike and Mickey. Luke is a father of John.\n      If X1 is a grandfather of Y1, Y1 is a grandchild of X1.\n      If X1 is male and X1 is a grandchild of Y1, X1 is a grandson of Y1.\n      Mike or Mickey is not female. Any person is male or female.\n      Who is a grandson of Luke?', 'Mike or Mickey.'],
  [1500, 'Tallinn is hardly in Latvia. Tallinn is in Latvia?', 'Likely false.'],
  [1521, 'It is not probable that John is a child of Mike. John is a child of Mike?', 'Probably false.'],
]
